# Konfigurasi Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Mempercepat proses build
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX dan Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Menggunakan Kotlin code style resmi
kotlin.code.style=official

# Optimasi konfigurasi Gradle
org.gradle.configuration-cache=true
